version: "3.1"

services:
  memcached1:
    image: "memcached:1.6"
    ports:
      - "11211:11211"

  memcached2:
    image: "memcached:1.6"
    ports:
      - "11212:11212"

  memcached3:
    image: "memcached:1.6"
    ports:
      - "11213:11213"
